apiVersion: v1
kind: Service

metadata:
  name: event-manager-service

spec:
  selector:
    app: event-manager

  type: NodePort

  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080