[agent]
  interval = "10s"
  flush_interval = "10s"

[[outputs.graphite]]
  servers = ["host.docker.internal:2003"]
  prefix = "system"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]

[[inputs.disk]]

[[inputs.diskio]]

[[inputs.net]]

[[inputs.system]]

[[inputs.processes]]
